
language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.dev.txt -r requirements.dist.txt
script:
  - python manage.py test
  - coverage run --source='tweeter' manage.py test
  - coverage report
  - codecov