# Generated by Django 2.1.1 on 2018-09-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
